### PR TITLE
Enhance downsize image functionality

### LINKED ISSUE #19: Enhance downsize image functionality
Downsize CLI module always applies a linear interpolator when resampling the image and this does not work for labelmaps. 

Even though a lot of different interpolators are created, linear interpolation is used always
https://github.com/DCBIA-OrthoLab/CMFreg/blob/master/Downsize/Downsize.cxx#L149

Suggestion to @juanprietob @ClementMirabel @pdedumast: Add an option to this CLI to allow selecting downsizing gray scale (linear interpolation) and label maps (nn interpolation)

### PR DESCRIPTION
**Pull request by allemangD**
Supports all the interpolators already defined:

    linear: LinearInterpolateImageFunction
    nearest: NearestNeighborInterpolateImageFunction
    bspline: BSplineInterpolateImageFunction

And WindowedSincInterpolateImageFunction with various window functions:

    hamming: HammingWindowFunction
    cosine: CosineWindowFunction
    welch: WelchWindowFunction
    lanczos: LanczosWindowFunction
    blackman: BlackmanWindowFunction

Radio selection is added to the module widget to choose the interpolator:

Interpolator radio selection

### CODE REVIEW

**Comment by bpaniagua** [comment]
Hi @allemangD 


These functionalities were not incorporated into DownsizeImage because we were trying to keep some of the parameters not shown to the users (that lack that type of expertise).

Can you provide more information why this is needed?
Thanks.

Bea

cc. @jcfr

**Comment by allemangD** [comment]
I think I misunderstood the intent of the linked issue https://github.com/DCBIA-OrthoLab/CMFreg/issues/19

The request seemed to be to enable the use of various types of interpolators. Since the other interpolators (bspline, hamming, etc) were already being created, I assumed it would be useful to add options for all of them. If that's undesirable from a user's perspective, those extra choices could easily be removed. 

> Add an option to this CLI to allow selecting downsizing gray scale (linear interpolation) and label maps (nn interpolation)

@bpaniagua, I could remove all but the linear and nn options, and rename those options in the UI to "Grayscale" and "Label Map". I.e. if the user selected "Grayscale" then linear interpolation would be used.

**Comment by bpaniagua** [comment]
I think interpolation is an ok term, I really like your idea to go for "label map" or "grayscale" and select nn or linear (respectively).

**Comment by allemangD** [comment]
@bpaniagua These changes are complete

Screenshot from 2020-09-02 10-30-55

**Review by bpaniagua — APPROVED** [review]
LGTM 👍

**Pull request merged**
