### PR TITLE
BUG: Remove BUILD_TESTING logic

### PR DESCRIPTION
**Pull request by phcerdan**
There is not Testing package sub directory to add.
Also the logic was switched.

```
if(NOT BUILD_TESTING)
  add_subdirectory(Testing)
endif()
```

Removed the block.

### CODE REVIEW

**Comment by phcerdan** [comment]
@juanprietob please merge this! Thanks :)

**Comment by jcfr** [comment]
To remind developer that there are no test, an other approach could be to change the code to:

```
#if(BUILD_TESTING)
#  add_subdirectory(Testing)
#endif()
```

**Review by jcfr — APPROVED** [review]

**Comment by phcerdan** [comment]
Commenting out the block, instead of deleting it, thanks @jcfr

**Comment by phcerdan** [comment]
Thanks @juanprietob

**Pull request merged**
